# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvsite atsakymą, Out reikšmė irgi pasikeis**

In [7]:
import numpy as np

1\. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [15]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2\. Sukurkite vektorių iš 10 nulių

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4\. Sukurkite vektorių iš 10 ketvertų

In [21]:
ketvertai = np.zeros(10, int)
ketvertai[:] = 4
ketvertai

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [23]:
np.arange(0 , 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [62]:
arrajus = np.arange(1,26)
matrica_array = np.array(arrajus)
matrica_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [64]:
matrica = matrica_array.reshape(5, 5)
matrica

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [66]:
matrica[2,1]

12

8\. Iš matricos ištraukite paskutinę eilutę.

In [67]:
matrica[4:5]

array([[21, 22, 23, 24, 25]])

9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [83]:
matrica[0:3, 0:3]  # kai dvimate matrica tiktai 2 galima, 3 negalima 1: 3 pvz, cia butu z . dabar yra x/y(tik 2)

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [102]:
matrica[1:4, 1:5] # x ir y

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [118]:
matrica[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [119]:
random_vektorius = np.random.rand(20)

In [120]:
random_vektorius

array([0.64293234, 0.20245473, 0.75672739, 0.64020361, 0.27567026,
       0.87052181, 0.15898878, 0.94556962, 0.76854303, 0.87561338,
       0.17467718, 0.62765843, 0.71197624, 0.82067979, 0.21428975,
       0.40887469, 0.3413695 , 0.44484111, 0.21235179, 0.73515968])

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [121]:
max(random_vektorius)

0.9455696209346032

In [122]:
random_vektorius.argmax() # indeksas

7

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [123]:
min(random_vektorius)

0.1589887839409021

In [124]:
random_vektorius.argmin()  # indeksas

6

15\. Atspausdinkite šios matricos duomenų tipą

In [125]:
random_vektorius.dtype

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [127]:
bandymas = np.arange(1,101)

In [128]:
bandymas

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [129]:
bandymas[bandymas > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [130]:
bandymas[bandymas % 7 == 0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

18\. Sukurkite tokią matricą:

In [9]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [131]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [10]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [132]:
matrica2= np.arange(2,1000)

In [134]:
rez = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)

In [135]:
rez

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [136]:
vektorius_is_sveiku = np.arange(1,101)

In [137]:
def ar_pirminis(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True

In [138]:
num_py_funkcija = np.vectorize(ar_pirminis)

In [139]:
vektorius_is_sveiku[num_py_funkcija(vektorius_is_sveiku)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])